custombucket = "awsprojs3bucket101"
table = "intellipaat"
databasehost = "aws-project-db.cuhhhiypppac.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "admin123"
s3database = "intellipaat"
kapp = "http://10.108.252.113/"
